[package]
name = "advent"
version = "0.1.0"
authors = ["ğŸ´â€â˜ ï¸ julie rogers ğŸ¦œ <jessica.mick.89@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"

# TODO test dependencies?
env_logger = "0.7.1"